---
- name: Role ensures that the socks tunnel is setup
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ansible-role-socks5-tunnel-nopassphrase
    
- name: WorkAround - WBC
  hosts: "{{ SERVER_WBC }}"
  gather_facts: false
  roles:
   - { role: WBC }
